### ISSUE TITLE
Reminder: Your action items for ProtoSchool's new local leadership model

### ISSUE THREAD

**Issue by terichadbourne** [ProtoSchool/bangalore#8]
@kishansagathiya @0zAND1z @vasa-develop 

As [announced](https://github.com/ProtoSchool/organizing/issues/84) in early March, ProtoSchool's new local leadership model centers around events as opposed to chapters and gives local event organizers more flexibility. If you haven't yet done so, there are a few steps you'll need to take as we transition to this new model, especially since it no longer relies on the use of GitHub.

**Tasks to complete by the end of April:**
- [ ] Review the [updated local leadership model](https://github.com/protoschool/organizing), including the guidelines on what qualifies as a ProtoSchool workshop
- [ ] Review the detailed [transition guide for chapter leaders](https://github.com/ProtoSchool/organizing/blob/master/COMMUNITY_MODEL_UPDATE.md)
- [ ] Decide whether you'd like us to archive this chapter repo or transfer it to other ownership ([details here](https://github.com/ProtoSchool/organizing/blob/master/COMMUNITY_MODEL_UPDATE.md#phasing-out-chapter-listings-and-chapter-repos))
- [x] [Subscribe to the ProtoSchool newsletter](https://school.us4.list-manage.com/subscribe?u=41e9e493c56c3865870435d91&id=967f7cf514), checking the box for local leadership updates

If you have questions on the new local leadership model or your options as we transition, please feel free to [email us](mailto:protoschool@protocol.ai). 

Thank you so much for your continued community leadership!

**Comment by vasa-develop** [comment]
@terichadbourne I will take a stab on these in a while.

**Comment by terichadbourne** [comment]
@vasa-develop  @0zAND1z  Just a quick reminder of the **deadline this Thursday, April 30**, to decide whether you'd like us to archive this chapter repo or transfer it to other ownership. (Please see above for more details.) If we don't hear back from you, we'll add a note about our new local leadership model and then archive the repo, which will prevent further edits. 

If you have questions on the new local leadership model or your options as we transition, please feel free to [email us](mailto:protoschool@protocol.ai).

**Comment by terichadbourne** [comment]
Hi @vasa-develop @0zAND1z. I'm working on archiving or transferring chapter repos this week. Have you decided which approach you'd like to take?

**Comment by vasa-develop** [comment]
@terichadbourne We have also decided to go with archiving the repo.
